

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-node-0-pvc
spec:
  storageClassName: "gp2-ae"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-node-0-logs-pvc
spec:
  storageClassName: "gp2-ae"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.logs}}

