# ethereum / geth account keys (keystore)
{{- $generatedPrivateJson := .Files.Get "new-network.plugin.secrets.json" | fromJson }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node-0-account-key-config

  labels:
    app: qubernetes
    name: quorum-node-0-account-key-config
data:
  key: |-


    {{ toJson ($generatedPrivateJson.genesisKeyStoreAccount | b64dec) }}
